# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/unimove_db
spring.datasource.username=unimove_user
spring.datasource.password=unimove_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG